spring:
  profiles:
    active: dev-postgres
  application:
    name: bizTree
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  structured:
    format:
      console: ecs  # Use ecs,'logstash' or 'gelf' for other common formats
  level:
    root: ERROR
    org:
      springframework: ERROR
    pro:
      mir0n: DEBUG

---
# Development Oracle
spring:
  config:
    activate:
      on-profile: dev-oracle
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/MIR0N
    driverClassName: oracle.jdbc.OracleDriver
    username: esq2025
    password: q        
#    username: ${DB_USERNAME:esquser}
#    password: ${DB_PASSWORD:esqpassword}   
  jpa:
    mapping-resources:
      - META-INF/oracle-tree-node.xml
      - META-INF/oracle-dictionary.xml
      - META-INF/oracle-entity.xml
      - META-INF/oracle-custom-field.xml
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
server:
  port: 3000

---
# Development Postgres
spring:
  config:
    activate:
      on-profile: dev-postgres
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:esq2025}
    username: esq2025
    password: q
#    username: ${DB_USERNAME:esquser}
#    password: ${DB_PASSWORD:esqpassword}   
  jpa:
    mapping-resources:
      - META-INF/postgres-tree-node.xml
      - META-INF/postgres-dictionary.xml
      - META-INF/postgres-entity.xml
      - META-INF/postgres-custom-field.xml
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 3000
