image:
  repository: esquire.enyman
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 3003

db:
  vendor: dev-postgres
  host: esquire-infra-postgres
  port: 5432
  name: esq2025
  username: esq2025
  password: q

messaging:
  brokerUrl: tcp://esquire-infra-amq-activemq:61616
  clientId: enyman
  consumerEnabled: "false"

logging:
  levelRoot: ERROR
  levelSf: ERROR
  levelMir0n: DEBUG
  levelDevelop: DEBUG
  levelMsg: DEBUG
  developLogPath: /tmp/enyMan-develop.log
  msgLogPath: /tmp/enyMan-msg.log
