apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-xxrod-secret
  labels:
    app: {{ .Release.Name }}-xxrod
type: Opaque
data:
  db-password: {{ .Values.db.password | b64enc | quote }}
