apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kcmaster-secret
  labels:
    app: {{ .Release.Name }}-kcmaster
type: Opaque
data:
  kc-admin-client-secret: {{ .Values.keycloak.adminClientSecret | b64enc | quote }}
