apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app: {{ .Release.Name }}-keycloak
spec:
  serviceName: {{ .Release.Name }}-keycloak
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-keycloak
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-keycloak
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["{{ .Values.keycloak.mode }}", "--import-realm"]
          ports:
            - containerPort: 8080
            - containerPort: 9000    # health endpoint
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keycloak-secret
                  key: admin-username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keycloak-secret
                  key: admin-password
            - name: KC_HOSTNAME
              value: {{ .Values.keycloak.hostname | quote }}
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_BACKCHANNEL
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY_HEADERS
              value: xforwarded
            {{- with .Values.keycloak.httpRelativePath }}
            - name: KC_HTTP_RELATIVE_PATH
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.keycloak.proxy }}
            - name: KC_PROXY
              value: {{ . | quote }}
            {{- end }}
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data/h2
  volumeClaimTemplates:
    - metadata:
        name: keycloak-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storage.storageClass }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
