apiVersion: v1
kind: ConfigMap
metadata:
  name: esquire-topology
  labels:
    app: esquire-topology
data:
  topology.yml: |
{{ .Values.topologyContent | default (.Files.Get .Values.topologyFile) | indent 4 }}
