apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-secret
  labels:
    app: {{ .Release.Name }}-keycloak
type: Opaque
data:
  admin-username: {{ .Values.keycloak.adminUsername | b64enc | quote }}
  admin-password: {{ .Values.keycloak.adminPassword | b64enc | quote }}
