apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-biztree-secret
  labels:
    app: {{ .Release.Name }}-biztree
type: Opaque
data:
  db-password: {{ .Values.db.password | b64enc | quote }}
