apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-biztree-config
  labels:
    app: {{ .Release.Name }}-biztree
data:
  SPRING_PROFILES_ACTIVE:            {{ .Values.springProfilesActive | default "" | quote }}
  BIZTREE_PORT:                      {{ .Values.service.port | quote }}
  DB_BIZTREE_VENDOR:                 {{ .Values.db.vendor | quote }}
  DB_BIZTREE_HOST:                   {{ .Values.db.host | quote }}
  DB_BIZTREE_PORT:                   {{ .Values.db.port | quote }}
  DB_BIZTREE_NAME:                   {{ .Values.db.name | quote }}
  DB_BIZTREE_USERNAME:               {{ .Values.db.username | quote }}
  AMQ_BROKER_URL:                    {{ .Values.messaging.brokerUrl | quote }}
  BIZTREE_MESSAGING_CLIENT_ID:       {{ .Values.messaging.clientId | quote }}
  BIZTREE_MESSAGING_CONSUMER_ENABLED: {{ .Values.messaging.consumerEnabled | quote }}
  LOG_LEVEL_ROOT:                    {{ .Values.logging.levelRoot | quote }}
  LOG_LEVEL_SF:                      {{ .Values.logging.levelSf | quote }}
  LOG_LEVEL_MIR0N:                   {{ .Values.logging.levelMir0n | quote }}
  LOG_LEVEL_DEVELOP:                 {{ .Values.logging.levelDevelop | quote }}
  LOG_LEVEL_MSG:                     {{ .Values.logging.levelMsg | quote }}
  DEVELOP_LOG_PATH:                  {{ .Values.logging.developLogPath | quote }}
  MSG_LOG_PATH:                      {{ .Values.logging.msgLogPath | quote }}
