apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-biztree
  labels:
    app: {{ .Release.Name }}-biztree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-biztree
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-biztree
    spec:
      containers:
        - name: biztree
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["java", "-jar", "app.jar"]
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-biztree-config
          env:
            - name: DB_BIZTREE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-biztree-secret
                  key: db-password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 5
