esquire:
  gateway:
    service-metrics:
      enabled: ${GW_SERVICE_METRICS_ENABLED:false} # Control whether to collect metrics for the gateway on backend services
server:
  port: ${GATEWAY_PORT:8080} 
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  webflux:
    problemdetails:
      enabled: true
  application:
    name: "gateway"
  cloud:
    gateway:
       #default-filters:
       #  - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST #RETAIN_UNIQUE
       globalcors:
         # globalcors somehow do not work: used custom config: see spring.security.cors
         add-to-simple-url-handler-mapping: true 
         cors-configurations:
           '[/**]':
             allowedOrigins: "http://localhost:4200"
             allowedHeaders: "*"
             allowedMethods: "*"
       routes:
        - id: keysmith-route
          uri: http://${KEYSMITH_HOST:biztree}:${KEYSMITH_PORT:3002}
          predicates:
            - Path=/esq-key
          metadata:
              allowedMethods:
                - GET
                - POST
          filters:
             #RETAIN_UNIQUE
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
            - RewritePath=/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: biztree-route
          uri: http://${BIZTREE_HOST:biztree}:${BIZTREE_PORT:3002}
          predicates:
            - Path=/esq,/esq-path,/esq-enode
          metadata:
              allowedMethods:
                - GET
                - POST
          filters:
             #RETAIN_UNIQUE
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
            - RewritePath=/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: pacman-route
          uri: http://${PACMAN_HOST:enyman}:${PACMAN_PORT:3003}
          predicates:
            - Path=/esq-cmd
            - Query=kind, ^(50|51|52|53|54|55)$     # kind=50,52,54: accounts and their shortcuts
          metadata:
            allowedMethods:
              - GET
              - POST
          filters:
            #RETAIN_UNIQUE
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
            - RewritePath=/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: enyman-route
          uri: http://${ENYMAN_HOST:enyman}:${ENYMAN_PORT:3003}
          predicates:
            - Path=/esq-cmd,/esq-dict,/esq-kinds
          metadata:
            allowedMethods:
              - GET
              - POST
          filters:
            #RETAIN_UNIQUE
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
            - RewritePath=/(?<segment>.*), /$\{segment}
            - TokenRelay=

#  autoconfigure:
#   exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
      allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed-headers: ["Authorization", "Content-Type", "X-Request-ID", "X-Correlation-ID", "X-Capture-Metrics"]
      allow-credentials: true
      max-age: 3600
      exposed-headers: ["X-Request-ID", "X-Correlation-ID","X-Response-Time", "Esq-Service-Time", "Esq-Backend-Time"]
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:esq-angular}
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            enable-cors: true
            issuer-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:esquire}
            authorization-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:esquire}/protocol/openid-connect/auth
            token-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:esquire}/protocol/openid-connect/token
            jwk-set-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:esquire}/protocol/openid-connect/certs
            user-info-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:esquire}/protocol/openid-connect/userinfo
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:esquire}/protocol/openid-connect/certs
info:
  app:
    name: "gateway"
    description: "Facade Esquire Server"
    version: "1.0.0"

logging:
  pattern:
    dateformat: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX,UTC"
  structured:
    format:
      console: ecs  # Use ecs,'logstash' or 'gelf' for other common formats
  level:
    root: ${LOG_LEVEL_ROOT:ERROR}
    org:
      springframework: ${LOG_LEVEL_SF:ERROR}
    pro:
      mir0n: ${LOG_LEVEL_MIR0N:ERROR}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    redis:
      enabled: false
endpoint:
    health:
      db:
        enabled: false
      probes:
        enabled: true
      show-details: always        