services:
  keycloak:
    container_name: esq-keycloak
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    image: esquire-keycloak:26.6.0
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: q
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HEALTH_ENABLED: "true"
    volumes:
      # Mount your local file into the magic import directory
      - ./import/esquire.json:/opt/keycloak/data/import/realm.json
      # have data volume mounted
      - ./data:/opt/keycloak/data
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n' >&3; grep 'HTTP/1.1 200 OK' <&3"]
      interval: 10s
      timeout: 5s
      retries: 5      
    networks:
      - esquirenet
networks:
  esquirenet:
    driver: "bridge"
      