apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keysmith
  labels:
    app: {{ .Release.Name }}-keysmith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-keysmith
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-keysmith
    spec:
      containers:
        - name: keysmith
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["java", "-jar", "app.jar"]
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-keysmith-config
          env:
            - name: DB_KEYSMITH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keysmith-secret
                  key: db-password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: esquire-topology
              mountPath: /etc/esquire
              readOnly: true
      volumes:
        - name: esquire-topology
          configMap:
            name: esquire-topology
