apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aukeep-secret
  labels:
    app: {{ .Release.Name }}-aukeep
type: Opaque
data:
  db-password: {{ .Values.db.password | b64enc | quote }}
