apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keysmith-secret
  labels:
    app: {{ .Release.Name }}-keysmith
type: Opaque
data:
  db-password: {{ .Values.db.password | b64enc | quote }}
  mq-password: {{ .Values.mq.password | default "" | b64enc | quote }}
