apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  labels:
    app: {{ .Release.Name }}-frontend
data:
  config.json: |
    {
      "apiBasePath": {{ .Values.config.apiBasePath | quote }},
      "keycloakUrl": {{ .Values.config.keycloakUrl | quote }},
      "keycloakRealm": {{ .Values.config.keycloakRealm | quote }},
      "keycloakClientId": {{ .Values.config.keycloakClientId | quote }}
    }
