name: esq-omnibus
services:
  keycloak:
    container_name: esq-keycloak
    image: quay.io/keycloak/keycloak:26.4.7
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: q
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HEALTH_ENABLED: "true"
    volumes:
      # Mount your local file into the magic import directory
      - ./import/esquire.json:/opt/keycloak/data/import/realm.json
      # have data volume mounted
      - ./data:/opt/keycloak/data
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n' >&3; grep 'HTTP/1.1 200 OK' <&3"]
      interval: 10s
      timeout: 5s
      retries: 5      
    networks:
      - esquirenet

  biztree:
    container_name: esq-biztree
    build:
      context: .
    image: esquire.biztree
    ports:
      - "3002:3002"
    environment:
      - BIZTREE_PORT=3002
      - LOG_LEVEL_ROOT=ERROR
      - LOG_LEVEL_SF=ERROR
      - LOG_LEVEL_MIR0N=DEBUG
      - DB_BIZTREE_VENDOR=dev-postgres
      - DB_BIZTREE_PORT=5432
      - DB_BIZTREE_NAME=esq2025
      #- DB_BIZTREE_VENDOR=dev-oracle
      #- DB_BIZTREE_PORT=1521
      #- DB_BIZTREE_NAME=MIR0N
      - DB_BIZTREE_HOST=host.docker.internal
      - DB_BIZTREE_USERNAME=esq2025
      - DB_BIZTREE_PASSWORD=q
    command: ["java", "-jar", "app.jar"]
    networks:
      - esquirenet

  enyman:
    container_name: esq-enyman
    build:
      context: .
    image: esquire.enyman
    ports:
      - "3003:3003"
    environment:
      - ENYMAN_PORT=3003
      - LOG_LEVEL_ROOT=ERROR
      - LOG_LEVEL_SF=ERROR
      - LOG_LEVEL_MIR0N=DEBUG
      - DB_ENYMAN_VENDOR=dev-postgres
      - DB_ENYMAN_PORT=5432
      - DB_ENYMAN_NAME=esq2025
      #- DB_ENYMAN_VENDOR=dev-oracle
      #- DB_ENYMAN_PORT=1521
      #- DB_ENYMAN_NAME=MIR0N
      - DB_ENYMAN_HOST=host.docker.internal
      - DB_ENYMAN_USERNAME=esq2025
      - DB_ENYMAN_PASSWORD=q
    command: ["java", "-jar", "app.jar"]
    networks:
      - esquirenet

  pacman:
    container_name: esq-pacman
    build:
      context: .
    image: esquire.pacman
    ports:
      - "3004:3004"
    environment:
      - PACMAN_PORT=3004
      - LOG_LEVEL_ROOT=ERROR
      - LOG_LEVEL_SF=ERROR
      - LOG_LEVEL_MIR0N=DEBUG
      - DB_PACMAN_VENDOR=dev-postgres
      - DB_PACMAN_PORT=5432
      - DB_PACMAN_NAME=esq2025
      #- DB_PACMAN_VENDOR=dev-oracle
      #- DB_PACMAN_PORT=1521
      #- DB_PACMAN_NAME=MIR0N
      - DB_PACMAN_HOST=host.docker.internal
      - DB_PACMAN_USERNAME=esq2025
      - DB_PACMAN_PASSWORD=q
    command: ["java", "-jar", "app.jar"]
    networks:
      - esquirenet

  gateway:
    container_name: esq-gateway
    build:
      context: .
    image: esquire.gateway
    ports:
      - "3000:7070"
    healthcheck:
      # Use localhost:7070 because this command runs INSIDE the container
      test: ["CMD", "curl", "-f", "http://localhost:7070/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    environment:
      - GATEWAY_PORT=7070
      - BIZTREE_PORT=3002
      - BIZTREE_HOST=biztree
      - ENYMAN_PORT=3003
      - ENYMAN_HOST=enyman
      - PACMAN_PORT=3004
      - PACMAN_HOST=pacman
      - BACKEND_HOST=localhost
      - KEYCLOAK_HOST=esq-keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=esquire
      - KEYCLOAK_CLIENT_ID=esq-angular
      - CORS_ALLOWED_ORIGINS=http://localhost:4200
      - LOG_LEVEL_ROOT=ERROR
      - LOG_LEVEL_SF=ERROR
      - LOG_LEVEL_MIR0N=DEBUG
      - GW_SERVICE_METRICS_ENABLED=true 
    command: ["java", "-jar", "app.jar"]
    depends_on:
      keycloak:
        condition: service_healthy    
    networks:
      - esquirenet

#  frontend:
#    container_name: esq-frontend
#    build:
#      context: .
##      secrets:
##        - npmrc        
#    image: esquire.frontend
#    ports:
#      - "4200:4200"
#    environment:
#      # These variables are injected into assets/config.json at container start
#      - BACKEND_HOST=localhost
#      - BACKEND_PORT=3000
#      - KEYCLOAK_FACADE_HOST=localhost
#      - KEYCLOAK_FACADE_PORT=8080
#      - KEYCLOAK_REALM=esquire
#      - KEYCLOAK_CLIENT_ID=esq-angular
#    # Command overrides angular.json for Docker without changing local code
#    command: >
#          /bin/sh -c "
#          envsubst < ./public/assets/config.json.template > ./public/assets/config.json && 
#          npx ng serve --host 0.0.0.0 --port 4200 --poll 2000
#          "
#    depends_on:
#      gateway:
#        condition: service_healthy
#    networks:
#      - esquirenet
#      
###    volumes:
###      - .:/app
###      - /app/node_modules # Prevents local node_modules from overwriting container's
### Mount ONLY the template as read-only
###      - ./public/assets/config.json.template:/public/assets/config.json.template:ro
##secrets:
##  npmrc:
##    file: ./.npmrc_composer 

networks:
  esquirenet:
    driver: "bridge"
   