services:
  enyman:
    build:
      context: .
    image: esquire.enyman
    ports:
      - "3003:3003"
    environment:
      - ENYMANTREE_PORT=3003
      - LOG_LEVEL_ROOT=ERROR
      - LOG_LEVEL_SF=ERROR
      - LOG_LEVEL_MIR0N=DEBUG
      - DB_ENYMAN_VENDOR=dev-postgres
      - DB_ENYMAN_PORT=5432
      - DB_ENYMAN_HOST=host.docker.internal
      - DB_ENYMAN_USERNAME=esq2025
      - DB_ENYMAN_PASSWORD=q
    command: ["java", "-jar", "app.jar"]
    networks:
      - esquirenet
networks:
  esquirenet:
    driver: "bridge"
   