apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gateway-config
  labels:
    app: {{ .Release.Name }}-gateway
data:
  GATEWAY_PORT:         {{ .Values.service.port | quote }}
  KEYCLOAK_HOST:        {{ .Values.keycloak.host | quote }}
  KEYCLOAK_PORT:        {{ .Values.keycloak.port | quote }}
  KEYCLOAK_REALM:       {{ .Values.keycloak.realm | quote }}
  KEYCLOAK_CLIENT_ID:   {{ .Values.keycloak.clientId | quote }}
  BIZTREE_HOST:         {{ .Values.backends.biztreeHost | quote }}
  BIZTREE_PORT:         {{ .Values.backends.biztreePort | quote }}
  ENYMAN_HOST:          {{ .Values.backends.enymanHost | quote }}
  ENYMAN_PORT:          {{ .Values.backends.enymanPort | quote }}
  PACMAN_HOST:          {{ .Values.backends.pacmanHost | quote }}
  PACMAN_PORT:          {{ .Values.backends.pacmanPort | quote }}
  KEYSMITH_HOST:        {{ .Values.backends.keysmithHost | quote }}
  KEYSMITH_PORT:        {{ .Values.backends.keysmithPort | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.cors.allowedOrigins | quote }}
  LOG_LEVEL_ROOT:       {{ .Values.logging.levelRoot | quote }}
  LOG_LEVEL_SF:         {{ .Values.logging.levelSf | quote }}
  LOG_LEVEL_MIR0N:      {{ .Values.logging.levelMir0n | quote }}
  LOG_LEVEL_DEVELOP:    {{ .Values.logging.levelDevelop | quote }}
  DEVELOP_LOG_PATH:     {{ .Values.logging.developLogPath | quote }}
