apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datasources
  labels:
    app: {{ .Release.Name }}
data:
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        uid: esq-loki
        url: {{ .Values.loki.url }}
        isDefault: true
        jsonData:
          maxLines: 1000
  tempo.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        uid: esq-tempo
        url: {{ .Values.tempo.url }}
        jsonData:
          httpMethod: GET
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        uid: esq-prometheus
        url: {{ .Values.prometheus.url }}
        isDefault: false
        jsonData:
          httpMethod: POST
