apiVersion: v1
kind: Service
metadata:
  # NB: service name == release name (esquire-infra-redis) so it matches the topology endpoint
  # redis://esquire-infra-redis:6379.
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
