apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    app: {{ .Release.Name }}-postgres
type: Opaque
data:
  username: {{ .Values.db.username | b64enc | quote }}
  password: {{ .Values.db.password | b64enc | quote }}
  db-name:  {{ .Values.db.name     | b64enc | quote }}
